# Generated by Django 5.2.3 on 2025-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='base_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='share_of_business',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='supplier',
            name='type',
            field=models.CharField(default='Direct', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='unit_of_measure',
            field=models.CharField(default='Unit', max_length=20),
        ),
    ]
