# Generated by Django 5.2.3 on 2025-06-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supplier_base_currency_supplier_gstin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_date',
            new_name='issue_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='PO0001', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
