# Generated by Django 5.2.3 on 2025-06-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_total_amount_purchaseorder_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierdiscount',
            old_name='discount_name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='supplierproductpricing',
            name='effective_date',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproductpricing',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproductpricing',
            name='unit_of_measure',
            field=models.CharField(default='Units', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='suppliercontract',
            name='terms',
            field=models.TextField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierproductpricing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='AlternateSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('lead_time_days', models.IntegerField()),
                ('alternate_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_for', to='core.supplier')),
                ('primary_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_for', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SpendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_center', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
